name: Build ESP32 Dev Firmware

on:
  push:
    branches:
      - esp32_dev
    tags:
    #   - '*.*.*'
    paths:
    - 'CHANGELOG_LATEST.md'
  workflow_dispatch:
    branches: [ esp32_dev ]

jobs:
        
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Version
        id: fetch_version
        run: |
             version=`grep -E '^#define EMSESP_APP_VERSION' ./src/version.h | awk '{print $3}' | sed 's/"//g'`
             echo "::set-output name=s::$version"

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          platformio upgrade
          platformio update

      - name: Build web
        run: |
          cd interface
          npm install
          npm run build

      - name: Build images
        run: |
          platformio run -e esp32-ci
          
      - name: Delete
        uses: dev-drprasad/delete-tag-and-release@v0.1.2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          delete_release: true 
          tag_name: esp32_dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Changelog
        run: cat RELEASENOTES_DEV.md CHANGELOG_LATEST.md > BODY.txt 

      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: BODY.txt
          name: ESP32 Development Build v${{steps.fetch_version.outputs.s}}
          tag_name: esp32_dev
          prerelease: true
          files: |
            ./build/firmware/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
